// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOU5fofXaGDKzWou_sglhO5ss-_BUyKn0',
    appId: '1:358842641404:web:d70d83db99d15268f96079',
    messagingSenderId: '358842641404',
    projectId: 'latepass-d0f19',
    authDomain: 'latepass-d0f19.firebaseapp.com',
    storageBucket: 'latepass-d0f19.firebasestorage.app',
    measurementId: 'G-Y44LXTSKBL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6fWtOyRRNiwzIkcRy1uZ1KPnhjermBU8',
    appId: '1:358842641404:android:726703207dc69223f96079',
    messagingSenderId: '358842641404',
    projectId: 'latepass-d0f19',
    storageBucket: 'latepass-d0f19.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNQGV6zU39YNF8DnpuLkZW5gmXrI6lgpQ',
    appId: '1:358842641404:ios:2f39094827faaad6f96079',
    messagingSenderId: '358842641404',
    projectId: 'latepass-d0f19',
    storageBucket: 'latepass-d0f19.firebasestorage.app',
    iosBundleId: 'com.example.latepass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNQGV6zU39YNF8DnpuLkZW5gmXrI6lgpQ',
    appId: '1:358842641404:ios:2f39094827faaad6f96079',
    messagingSenderId: '358842641404',
    projectId: 'latepass-d0f19',
    storageBucket: 'latepass-d0f19.firebasestorage.app',
    iosBundleId: 'com.example.latepass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOU5fofXaGDKzWou_sglhO5ss-_BUyKn0',
    appId: '1:358842641404:web:e0747393d5e02ad9f96079',
    messagingSenderId: '358842641404',
    projectId: 'latepass-d0f19',
    authDomain: 'latepass-d0f19.firebaseapp.com',
    storageBucket: 'latepass-d0f19.firebasestorage.app',
    measurementId: 'G-SD2FN10Z7B',
  );
}
